openapi: 3.0.0
info:
  title: Auth
  description: API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: user register successfully
  /login:
    post:
      tags:
        - Auth
      requestBody:
        description: user login request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: user login successfully
